-- TipoDocumento equivalencias IdTrabajo 10008 desde HomologacionTipoDocumento.xlsx
-- Origen: columna C (codigo Codelco) -> Destino: F + descripcion Salfa (columna E)
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

DECLARE @IdTrabajo INT = 10008;
DECLARE @Codelco   NVARCHAR(50) = '1207996652';
DECLARE @Salfa     NVARCHAR(50) = '1207996803';

DELETE FROM TransmittalSyncEquivalencia
WHERE IdTrabajo = @IdTrabajo
  AND ACXProjectIdOrigen = @Codelco
  AND ACXProjectIdDestino = @Salfa
  AND Tipo = N'TipoDocumento';

INSERT INTO TransmittalSyncEquivalencia
    (IdTrabajo, ACXProjectIdOrigen, ACXProjectIdDestino, Tipo, ValorOrigen, ValorDestino)
VALUES
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'CRT', N'CDD-Criterios de Dise' + NCHAR(241) + N'o'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'CUB', N'CUB-Cubicaci' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'ESP', N'ETT-Especificaci' + NCHAR(243) + N'n T' + NCHAR(233) + N'cnica'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'HDD', N'HDD-Hoja de Datos'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'INF', N'ITE-Informe T' + NCHAR(233) + N'cnico'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'INS', N'INS-Instructivo'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'LST', N'LIS-Lista'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'MAT', N'MOD-Modelo Bim'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'M3D', N'MOD-Modelo Bim'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'M4D', N'MOD-Modelo Bim'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'MDC', N'MDC-Memoria de C' + NCHAR(225) + N'lculo'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'MIN', N'MDR-Minuta de Reuni' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'MNL', N'MAN-Manual'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'NDP', N'NDP-Nube de Puntos'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'NOR', N'NOR-Norma'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'PRO', N'PRO-Procedimiento'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'PST', N'PRE-Presentaci' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'RCP', N'REP-Reporte'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'REQ', N'REQ-Requisici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'RGS', N'REG-Registro'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'SDI', N'SDI-Solicitud de Informaci' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'STD', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'000AR', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'001AR', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'100AR', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'101AR', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'102AR', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'200AR', N'PDO-Plano de Dise' + NCHAR(241) + N'o'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'201AR', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'300AR', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'301AR', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'400AR', N'PDM-Plano de Montaje'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'500AR', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'600AR', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'000AT', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'001AT', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'002AT', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'003AT', N'CFG-Configuraci' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'004AT', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'011AT', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'012AT', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'100AT', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'101AT', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'102AT', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'103AT', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'104AT', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'105AT', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'200AT', N'PDO-Plano de Dise' + NCHAR(241) + N'o'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'201AT', N'CCD-Cuadro de Consumos y Demandas'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'202AT', N'DUN-Diagrama Unilineal'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'203AT', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'204AT', N'DCO-Diagrama de Conexionado'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'205AT', N'PCA-Plano de Canalizaciones'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'206AT', N'PMT-Plano de Malla de Tierra'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'207AT', N'DCO-Diagrama de Conexionado'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'208AT', N'DCO-Diagrama de Conexionado'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'209AT', N'DCO-Diagrama de Conexionado'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'210AT', N'DGM-Diagrama'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'220AT', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'221AT', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'222AT', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'223AT', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'224AT', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'225AT', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'226AT', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'227AT', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'228AT', N'CFG-Configuraci' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'229AT', N'CFG-Configuraci' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'300AT', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'400AT', N'PDM-Plano de Montaje'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'411AT', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'412AT', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'413AT', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'500AT', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'600AT', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'000CA', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'100CA', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'101CA', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'102CA', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'103CA', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'200CA', N'PDO-Plano de Dise' + NCHAR(241) + N'o'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'201CA', N'DPI-Diagrama de Procesos E Instrumentaci' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'202CA', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'203CA', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'204CA', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'205CA', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'206CA', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'300CA', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'301CA', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'303CA', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'400CA', N'PDM-Plano de Montaje'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'500CA', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'502CA', N'ISO-Isom' + NCHAR(233) + N'trico'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'600CA', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'000OH', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'100OH', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'101OH', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'102OH', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'103OH', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'200OH', N'PDO-Plano de Dise' + NCHAR(241) + N'o'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'201OH', N'DPI-Diagrama de Procesos E Instrumentaci' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'202OH', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'203OH', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'204OH', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'205OH', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'206OH', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'300OH', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'301OH', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'303OH', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'400OH', N'PDM-Plano de Montaje'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'500OH', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'502OH', N'ISO-Isom' + NCHAR(233) + N'trico'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'600OH', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'000CI', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'001CI', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'100CI', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'101CI', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'200CI', N'PDO-Plano de Dise' + NCHAR(241) + N'o'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'201CI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'202CI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'203CI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'204CI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'205CI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'206CI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'207CI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'208CI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'209CI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'210CI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'300CI', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'400CI', N'PDM-Plano de Montaje'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'500CI', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'600CI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'100CB', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'200CB', N'PDO-Plano de Dise' + NCHAR(241) + N'o'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'400CB', N'PDM-Plano de Montaje'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'500CB', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'000CO', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'001CO', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'002CO', N'PDM-Plano de Montaje'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'003CO', N'CFG-Configuraci' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'100CO', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'101CO', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'102CO', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'103CO', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'104CO', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'200CO', N'PDO-Plano de Dise' + NCHAR(241) + N'o'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'201CO', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'202CO', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'203CO', N'PCA-Plano de Canalizaciones'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'204CO', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'205CO', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'206CO', N'DUN-Diagrama Unilineal'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'231CO', N'CCD-Cuadro de Consumos y Demandas'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'232CO', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'233CO', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'234CO', N'DIN-Diagrama de Interconexionado'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'235CO', N'DCO-Diagrama de Conexionado'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'236CO', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'237CO', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'238CO', N'PPR-Protocolo de Pruebas'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'300CO', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'400CO', N'PDM-Plano de Montaje'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'413CO', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'414CO', N'PCA-Plano de Canalizaciones'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'415CO', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'500CO', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'501CO', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'502CO', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'600CO', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'000EL', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'001EL', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'002EL', N'PDM-Plano de Montaje'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'003EL', N'CFG-Configuraci' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'004EL', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'100EL', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'101EL', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'102EL', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'103EL', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'104EL', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'105EL', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'106EL', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'107EL', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'108EL', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'109EL', N'DUN-Diagrama Unilineal'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'110EL', N'DUN-Diagrama Unilineal'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'111EL', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'200EL', N'PDO-Plano de Dise' + NCHAR(241) + N'o'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'201EL', N'CCD-Cuadro de Consumos y Demandas'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'202EL', N'DUN-Diagrama Unilineal'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'203EL', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'204EL', N'DCO-Diagrama de Conexionado'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'205EL', N'PCA-Plano de Canalizaciones'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'206EL', N'PMT-Plano de Malla de Tierra'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'207EL', N'DCO-Diagrama de Conexionado'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'208EL', N'DIN-Diagrama de Interconexionado'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'209EL', N'DCO-Diagrama de Conexionado'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'210EL', N'DGM-Diagrama'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'211EL', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'212EL', N'PAL-Plano de Alumbrado'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'213EL', N'DUN-Diagrama Unilineal'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'300EL', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'400EL', N'PDM-Plano de Montaje'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'401EL', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'402EL', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'403EL', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'404EL', N'DGM-Diagrama'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'500EL', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'600EL', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'000ES', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'001ES', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'100ES', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'200ES', N'PDO-Plano de Dise' + NCHAR(241) + N'o'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'201ES', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'202ES', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'203ES', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'204ES', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'205ES', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'206ES', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'207ES', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'208ES', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'209ES', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'210ES', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'300ES', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'301ES', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'302ES', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'400ES', N'PDM-Plano de Montaje'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'500ES', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'600ES', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'000GE', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'100GE', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'101GE', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'102GE', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'103GE', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'104GE', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'105GE', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'200GE', N'PDO-Plano de Dise' + NCHAR(241) + N'o'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'201GE', N'MOD-Modelo'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'202GE', N'MOD-Modelo'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'203GE', N'MOD-Modelo'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'204GE', N'MOD-Modelo'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'205GE', N'MOD-Modelo'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'206GE', N'MOD-Modelo'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'207GE', N'MOD-Modelo'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'000GM', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'100GM', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'101GM', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'102GM', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'103GM', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'200GM', N'PDO-Plano de Dise' + NCHAR(241) + N'o'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'300GM', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'400GM', N'PDM-Plano de Montaje'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'500GM', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'600GM', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'000HD', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'100HD', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'101HD', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'200HD', N'PDO-Plano de Dise' + NCHAR(241) + N'o'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'201HD', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'202HD', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'300HD', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'400HD', N'PDM-Plano de Montaje'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'500HD', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'600HD', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'000II', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'001II', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'002II', N'CFG-Configuraci' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'100II', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'101II', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'102II', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'103II', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'200II', N'PDO-Plano de Dise' + NCHAR(241) + N'o'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'201II', N'CCD-Cuadro de Consumos y Demandas'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'202II', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'241II', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'242II', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'243II', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'244II', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'245II', N'DBL-Diagrama de Bloques'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'246II', N'DCO-Diagrama de Conexionado'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'300II', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'400II', N'PDM-Plano de Montaje'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'500II', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'600II', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'000ME', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'001ME', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'100ME', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'101ME', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'102ME', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'103ME', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'104ME', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'200ME', N'PDO-Plano de Dise' + NCHAR(241) + N'o'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'201ME', N'DPI-Diagrama de Procesos E Instrumentaci' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'300ME', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'301ME', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'400ME', N'PDM-Plano de Montaje'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'500ME', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'600ME', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'000MI', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'001MI', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'100MI', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'102MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'103MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'200MI', N'PDO-Plano de Dise' + NCHAR(241) + N'o'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'201MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'202MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'203MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'204MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'205MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'206MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'207MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'208MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'209MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'210MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'211MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'212MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'213MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'214MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'215MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'216MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'217MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'218MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'219MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'220MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'300MI', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'400MI', N'PDM-Plano de Montaje'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'500MI', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'600MI', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'000PR', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'100PR', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'101PR', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'200PR', N'PDO-Plano de Dise' + NCHAR(241) + N'o'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'201PR', N'DPI-Diagrama de Procesos E Instrumentaci' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'202PR', N'DPI-Diagrama de Procesos E Instrumentaci' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'300PR', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'400PR', N'PDM-Plano de Montaje'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'500PR', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'600PR', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'000SA', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'100SA', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'101SA', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'200SA', N'PDO-Plano de Dise' + NCHAR(241) + N'o'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'201SA', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'202SA', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'300SA', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'400SA', N'PDM-Plano de Montaje'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'500SA', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'600SA', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'000TR', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'100TR', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'200TR', N'PDO-Plano de Dise' + NCHAR(241) + N'o'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'300TR', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'400TR', N'PDM-Plano de Montaje'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'500TR', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'600TR', N'PLA-Plano'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'000VC', N'EST-Est' + NCHAR(225) + N'ndar'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'100VC', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'101VC', N'PDG-Plano de Disposici' + NCHAR(243) + N'n General'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'102VC', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'200VC', N'PDO-Plano de Dise' + NCHAR(241) + N'o'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'201VC', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'202VC', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'203VC', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'300VC', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'301VC', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'302VC', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'303VC', N'PDN-Plano de Disposici' + NCHAR(243) + N'n'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'400VC', N'PDM-Plano de Montaje'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'500VC', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'501VC', N'PDD-Plano de Detalles'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'502VC', N'ISO-Isom' + NCHAR(233) + N'trico'),
(@IdTrabajo, @Codelco, @Salfa, N'TipoDocumento', N'600VC', N'PLA-Plano');

SELECT COUNT(*) AS TipoDocumentoActivos
FROM TransmittalSyncEquivalencia
WHERE IdTrabajo = @IdTrabajo AND Tipo = N'TipoDocumento' AND Activo = 1;
